FROM node:18-alpine
WORKDIR /usr/src/app

RUN apk add --no-cache \
  python3 \
  make \
  g++ \
  cairo-dev \
  jpeg-dev \
  pango-dev \
  giflib-dev

COPY package*.json ./
RUN npm install

EXPOSE 3000